src/android_main.cpp, src/thd_dbus_interface.cpp, src/thd_engine.cpp, src/thd_trip_point.h
Hi there,
I just ran the latest version of thermal daemon through cppcheck and it found some minor issues that I've attended to with these fixes.
One more thing, the current release number of thermal_daemon is 1.41,  my concern is that at some point the release number will be bumped to 1.5 which is actually smaller than 1.41 in debian packaging terms, so it makes versioning the package tricky (since 5 is less than 41).   Is there a rationale behind the current versioning scheme? I was expecting a 1.4.3 version since the previous tags were 1.4.1, 1.4.2.  
Regards, Colin
=> Misc fixes for thermal daemon

README.txt, data/thermald.conf, man/thermald.8, src/main.cpp
A few small fixes to documentation plus a typo fix in the the command line option --ignore-cpuid-check
And two fixes we've been carrying in Ubuntu for a release cycle so it's timely I asked for these to be pulled into thermald since they need to be upstreamed after a lot of use.
=> Minor spelling fixes in docs, README and one typo in command line options

data/thermald.service.in, src/thd_engine_default.cpp
Just two mainly cosmetic changes, one to suppress messages in systemd when thermald won't start (for example on a VM) and one to remove !! exclamation marks that make users a bit scared.
=> couple of minor changes, mainly to make user experience more friendly

src/main.cpp, src/thd_trt_art_reader.cpp
We've been seeing null pointer deferences on some Intel devices that
support _TRT and _ART ACPI objects.  This is due to a typo in
parse_target_devices() where a non-existant trt object is being pushed
onto a trt vector instead of the art vector.  This causes a NULL pointer
deference in add_active_trip_point() when performing the following:
union art_object *object = (union art_object *) rel_obj.art_objects[j];
=> Fix null pointer deferences with _ART active trip points (LP: #1480821)

src/thd_cdev.cpp, src/thd_cdev_rapl.cpp
Users have noticed some extraneous syslog messages that seem to be occurring frequently, so I think we should turn the info messages into debug.
=> minor changes to reduce syslog messages

tools/thermal_monitor/mainwindow.h
Building on a clean system produces compiler errors for the thermal_monitor.
Adding the relevant headers in resolves the issue and compiles cleanly.
Errors Produced:
mainwindow.h:72:5: error: ‘QLabel’ does not name a type
QLabel *sensor_label;
^
mainwindow.h:73:5: error: ‘QLabel’ does not name a type
QLabel *sensor_temp;
^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:28:9: error: ‘QMessageBox’ was not declared in this scope
QMessageBox msgBox;
^
main.cpp:34:9: error: ‘msgBox’ was not declared in this scope
msgBox.setText(str);
^
main.cpp:35:35: error: ‘QMessageBox’ is not a class or namespace
msgBox.setStandardButtons(QMessageBox::Abort);
^
main.cpp:39:14: error: ‘QMessageBox’ is not a class or namespace
case QMessageBox::Abort:
^
Makefile:280: recipe for target 'main.o' failed …
=> tools/thermal_monitor: Repair header includes

src/thd_cdev_rapl.h
CoverityScan picked up this bug:
** CID 11165:  Uninitialized members  (UNINIT_CTOR)
/src/thd_cdev_rapl.h: 60 in cthd_sysfs_cdev_rapl::
cthd_sysfs_cdev_rapl(unsigned int, int)()
Initialize bios_locked to false.
=> Initialize bios_locked to false

man/thermal-conf.xml.5, tools/thermal_monitor/main.cpp, tools/thermal_monitor/mainwindow.cpp, tools/thermal_monitor/mainwindow.h
Fix several typos of "confirm" to "conform"
=> manual: thermal-conf.xml: fix typos, "confirm" -> "conform"

src/thd_cdev_modem.cpp, src/thd_msr.cpp
get_modem_property currently returns THD_SUCCESS when a value is sometimes
not fetched.  This fix ensures THD_SUCCESS is only returned when value is
correctly fetched.  Bug found with scan-build static analysis:
src/thd_cdev_modem.cpp:245:10: warning: Assigned value is garbage or undefined
online = online_state;
^ ~~~~~~~~~~~~
src/thd_cdev_modem.cpp:258:14: warning: Assigned value is garbage or undefined
throttling = enabled;
^ ~~~~~~~
=> thermald: thd_cdev_modem: only return THD_SUCCESS if a value is fetched

src/thd_kobj_uevent.cpp
The recv read buffer may fill completely, leaving the buffer not
null terminated which is a hazard with string handling this buffer.
Check that the recv has enough data to null terminate the buffer
and also add a fast path return if the buffer is too short null
terminate.
=> check for recv failure and ensure buffer is null terminated

src/thd_cdev.cpp
This fixes an issue discovered by static analysis with
CoverityScan.
CoverityScan CID#157084 ("Uninitialized scalar value")
=> thd_cdev: ensure _target_value is initialized

src/thd_engine.cpp
The preference value was just parsed by phd_parser.cpp but not forwarded to the engine.
Check if the platform matched the id given by the xml file before apllying the preference value.
=> Load the preference value provided by the xml file

src/main.cpp
It is possible for a signal to occur before the thermald engine
is up and running and hence trying to call the terminate method
will result in a segmentation fault. Check to see if thd_engine
is non-null before invoking thd_engine_terminate.
Fixes bug http://bugs.launchpad.net/bugs/1677427
Note: I was able to reproduce the bug by inserting a
kill(getpid(), SIGTERM) after the signal handler was installed
and before the thermald engine is started to reliably trip the
issue. There is just a very small window where this bug can
actually can occur.
=> Don't terminate the thermald engine if thd_engine is null

Android.mk, src/thd_engine_default.cpp, src/thd_trip_point.h
Right now it seems to be impossible to compile thermal_daemon for Android:
- The build file is missing several source files. I've removed the existing list and copied the new list directly from `Makefile.am` (except for `thd_dbus_interface.cpp` and `thd_cdev_modem.cpp` because that requires DBUS which is not available on Android)
- There are a few compile errors because the DBUS code is not always properly guarded by checking if `GLIB_SUPPORT` is defined. I've added checks where necessary.
- There was a missing `return` statement in a method where an exception was disabled because Android disables them by default. That method seems to be only used from DBUS code so I've just disabled it entirely for Android.
Compiles successfully in Android N tree.
=> Android build fixes

man/thermald.8, src/thd_cpu_default_binding.cpp, src/thd_engine.cpp
These were discovered from the Debian Lintian checks, just minor mistakes that are cosmetic.
=> A few minor fixes in spelling and grammar

src/thd_kobj_uevent.h, src/thd_model.cpp, src/thd_trip_point.cpp
Found while building thermald for Yocto based Intel BSPs. Yocto allows users to build with musl/glibc and for x32 arch as well.
=> Fix issues with musl and x32

src/thd_cdev.cpp
When the trip point is off, it will call thd_cdev_set_state(state=0)
to update cdev state.
if zone_trip_limits.size() == 0, it means all trip points using this cdev
are off. It needs to set this cdev to min state (target_state_valid = 0).
Signed-off-by: Bin Yang <bin.yang@intel.com>
=> fix cdev state error while trip point is off

src/thd_zone.cpp
%zu instead of %lu, otherwise on 32 bit:
| ../git/src/thd_zone.cpp: In member function 'void cthd_zone::sort_and_update_poll_trip()':
| ../git/src/thd_zone.cpp:106:16: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'std::vector<cthd_trip_point>::size_type' {aka 'unsigned int'} [-Werror=format=]
|   thd_log_debug("sort_and_update_poll_trip: trip_points_size =%lu\n",
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|     trip_points.size());
=> Use correct format specifier for size_t

src/thd_cpu_default_binding.cpp, src/thd_parse.cpp
thd_parse.cpp: parse_new_platform_info and parse_new_trip_point
executed the initializations without the NULL check of xml node
parse result. Added null check for xml parsed output.
thd_cpu_default_binding.cpp: thd_engine->get_zone could potentially
return NULL and the function do_default_binding could dereference
a NULL pointer. Hence, added a NULL check for zone.
=> Klockwork: Modified the code with NULL checks for xml parsed output.

Android.mk, src/android_main.cpp
As per the new VNDK rules, vendor applications are expected to use
/data/vendor partition for all the data files.
Previously, the data files were created in /data/misc folder which
caused cts failures. Hence moving the data files creation to
/data/vendor partition.
=> Android: Changing the conf dir to 'vendor' instead of 'misc'

Android.mk, src/android_main.cpp, src/thermald.h
As per google's VNDK rules, vendor executables are supposed to link to an
allowed set of libraries (static and shared) and are supposed to use only
allower headers in the vendor code.
Following are the changes:
1. libicuuc no longer shall be linked in vendor application code.
2. Use log/log.h instead of cutils/log.h
3. Use cutils/android_filesystem_config.h instead of
private/android_filesystem_config.h.
VNDK reference: https://source.android.com/devices/architecture/vndk
=> Adding changes in the static library link and headers for VNDK compliance

Android.mk
For those builds with VNDK disabled, the libicuuc removal would break
the compilation. Hence, adding the library for builds in which VNDK
is disabled.
=> Modified the makefile to include libicuuc library for VNDK disabled builds

src/thd_parse.cpp
Change initializes the cooling device variable debounce_interval
to 0. The cdev variable used is declared in the stack.
debounce_interval was not initialized to a default value.
Initialize debounce_interval to 0 so that the variable is not
used uninitialized.
=> thd_parse: Fixing the klocwork issue reported

Android.mk, src/thd_trt_art_reader.cpp, src/thermald.h
For user builds, info and debug logs are not expected to be present.
Most thermal daemon logs are info or debug level, and surface in eng,
user and userdebug build variants. This violates the SDL requirement
which prohibits debug and info logs in user builds. So, adding a
conditional compilation define for user build to avoid debug and info
logs from thermal daemon.
=> Log reduction for user builds

src/thd_parse.cpp
Currently when parse_init calls xmlDocGetRootElement and this fails
the allocation of doc is not freed leading to a memory leak. Fix
this by free'ing doc on this specific error exit path.
=> thd_parse: fix memory leak when xmlDocGetRootElement fails

src/thd_rapl_power_meter.cpp
Klocwork issue's message:
'this->thd_attr.flags' might not be initialized
in this constructor.
'this->thd_attr.stack_base' might not be initialized
in this constructor.
'this->thd_attr.stack_size' might not be initialized
in this constructor.
'this->thd_attr.guard_size' might not be initialized
in this constructor.
'this->thd_attr.sched_policy' might not be initialized
in this constructor.
'this->thd_attr.sched_priority' might not be initialized
in this constructor.
Solution:
Initialize 'this->thd_attr' to avoid this issue.
Issues:
#93963, #93964, #93965, #93966, #93967, #93968
Change-Id: I895be238b88e26fa44b5f24b123d781e2616b26f
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-81220
Signed-off-by: Sun Xinx <xinx.sun@intel.com>
Reviewed-on: https://android.intel.com:443/671272
=> thermal-daemon: Fix klocwork critical issues

Android.mk
- Issue : As per feedback, it is observed that thermal daemon
is generating huge logs in android userdebug build.
- Fix : Allowing only Error, Warning and Fatal logs in user
and userdebug build for android OS.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-84501
Signed-off-by: ashish18590 <ashish18590@gmail.com>
=> [Android][ThermalD] : Limiting thermal daemon logs

Makefile.am, configure.ac
Fixes #206.
Had to include `-Werror` in the check because otherwise clang only warns about the unsupported flag and doesn't fail the check as it should have.
```
AX_CHECK_COMPILE_FLAG([-Werror ${flag}],
```
This is the output from my `./configure`. It excludes exactly the flags that were problematic.
```
checking whether C compiler accepts -Werror -Wall... yes
checking whether C compiler accepts -Werror -Wclobbered... no
checking whether C compiler accepts -Werror -Wempty-body... yes
checking whether C compiler accepts -Werror -Werror... yes
checking whether C compiler accepts -Werror -Wformat... yes
checking whether C compiler accepts -Werror -Wignored-qualifiers... yes
checking whether C compiler accepts -Werror -Wmissing-field-initializers... yes
checking whether C compiler accepts …
```
=> [👌 IMPROVE] Check for flag support - specifically in support of clang

configure.ac
AX_CHECK_COMPILE_FLAG is usually part of separate autoconf package,
called autoconf-archive, and on some distributions is not installed by
default.
When this macro is not present but user generates configure script,
it will complain with not so obvious message.
This commit fixes this by emitting clear message what is missing, so
user knows what to do next.
=> Check if AX_CHECK_COMPILE_FLAG is present.

src/thd_trip_point.cpp
Error log:
../git/src/thd_trip_point.cpp: In member function 'bool cthd_trip_point::thd_trip_point_check(int, unsigned int, int, bool*)':
| ../git/src/thd_trip_point.cpp:250:19: error: format '%ld' expects argument of type 'long int', but argument 6 has type 'time_t' {aka 'long long int'} [-Werror=format=]
|   250 |      thd_log_info("Too early to act zone:%d index %d tm %ld\n",
musl 1.2.0 have new feature:
time_t is now 64-bit on all archs (not just 64-bit archs)
Commit id:
https://git.musl-libc.org/cgit/musl/commit/?id=38143339646a4ccce8afe298c34467767c899f51
Release note link for musl 1.2.0:
https://git.musl-libc.org/cgit/musl/diff/
use %jd and typecast with intmax_t which is maximum width integer type
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
=> thd_trip_point: fix 32-bit build error with musl v1.2.0

src/thd_engine.cpp, tools/thermal_monitor/qcustomplot/qcustomplot.cpp
There are a couple of spelling mistakes, fix these. Also remove
trailing spaces that occur before \n newline.
=> Fix a couple of spelling mistakes and remove spaces before \n char

src/thd_engine_default.cpp
This allows the XML cooling device settings to override the default
ones.
It applies to platform-level (not trip-level) definitions.
Signed-off-by: Ali MJ Al-Nasrawy <alimjalnasrawy@gmail.com>
=> honor XML cooling device config

data/thermald.service.in
It is not useful to run thermald on a virtualized system, and doing so
will simply result in log output without any real benefit. Add the
appropriate option to not start in a virtualized environment.
See #237
=> data: Add ConditionVirtualization=no to systemd service

configure.ac
This will fix the following build failure which is related to glib:
```
In file included from /home/buildroot/autobuild/run/instance-1/output-1/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gthread.h:32:0,
from /home/buildroot/autobuild/run/instance-1/output-1/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gasyncqueue.h:32,
from /home/buildroot/autobuild/run/instance-1/output-1/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib.h:32,
from src/thermald.h:70,
from src/thd_dbus_interface.cpp:25:
src/thd_dbus_interface.cpp: In function 'GType pref_object_get_type()':
/home/buildroot/autobuild/run/instance-1/output-1/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gatomic.h:128:15: error: …
```
=> configure.ac: allow the user to disable -Werror

src/thd_engine.cpp
The path was missing the /sys prefix, rendering the test useless. Add
the appropriate prefix and also a comment explaining why we do this.
=> Fix path for Lenovo kill-switch heuristic

src/thd_engine_adaptive.cpp, src/thd_engine_adaptive.h
I'll probably push more stuff, but should be acceptable in theory.
With these changes, I can fully unpack the DPTF data on the X1C8 (still useless obviously), without it thermald falls on its feet when it encounters the second data vault object in the compressed data.
=> adaptive fixes

configure.ac, src/thd_adaptive_types.h, src/thd_engine_adaptive.cpp
On Slackware, stdint.h and inittypes.h are not implicitly included,
so `uint64_t` and `PRIu64` will not be recognized. This is fixed by
explicitly including those headers.
Also, check for and enable C++0x support because current code is using it.
=> Fixed gcc 5.x compilation and unrecognized types

src/thd_engine_adaptive.cpp, src/thd_engine_adaptive.h
The condition and comparison fields of the condition struct are used
for arbitrary integer values, not just the ones in their respective enum
fields. Reflect this by using an integer type and not an enum type.
This fixes the build with clang.
Fixes #284
I see there are tests in `tests/`, but I did not run any of them since I am not sure how.
=> thd_engine_adapive: Change some struct field types

README.txt, data/thermal-conf.xml, man/thermald.8, src/android_main.cpp, src/thd_cdev_modem.cpp, src/thd_engine.h, src/thd_parse.cpp, src/thd_zone.cpp, test/test6.xml, test/test_cases.txt, tools/thermal_monitor/qcustomplot/changelog.txt, tools/thermal_monitor/qcustomplot/qcustomplot.cpp, tools/thermal_monitor/qcustomplot/qcustomplot.h, tools/thermal_monitor/thermaldinterface.cpp
There are a handful of spelling mistakes in comments and literal
strings found by codespell. Fix these.
=> Fix spelling mistakes found using codespell

src/thd_engine_adaptive.cpp
As can be seen in https://github.com/intel/dptf/blob/master/ESIF/Products/ESIF_LIB/Sources/esif_lib_datavault.c#L980 ,
we should be testing for whether the compressed flag is set and not whether
the flags field is equal to the compressed flag.
=> Fix test for compressed data vaults

src/thd_pid.cpp
`err_sum` was initialized by `expression / ki`
resulting in `err_sum == -inf` when `ki == 0`
This broke output calculation,
because `0.0 * -inf` produced `-NaN`, overriding
proportional and derivative component influence.
=> fix division by zero in pid init

tools/thermal_monitor/thermaldinterface.cpp
fix https://github.com/intel/thermal_daemon/issues/311
=> fix: Wrong variable cdev_count is used to report the GetZoneCount error

src/thd_engine.cpp
These were added upstream in the kernel already.
Note that I have *not* tested this. As such, it might be that further changes are needed, however, I am assuming that simply adding the CPU IDs is sufficient.
=> Add RaptorLake CPU models

Makefile.am, configure.ac, src/main.cpp, src/thd_adaptive_types.h, src/thd_cdev.cpp, src/thd_cdev.h, src/thd_cdev_rapl.cpp, src/thd_engine.cpp, src/thd_engine.h, src/thd_engine_adaptive.cpp, src/thd_engine_adaptive.h, src/thd_engine_default.cpp, src/thd_engine_default.h, src/thd_gddv.cpp, src/thd_gddv.h, src/thd_int3400.cpp, src/thd_trip_point.cpp, src/thd_trip_point.h, src/thd_zone_dynamic.cpp, src/thd_zone_dynamic.h, tools/thermal_monitor/COPYING, tools/thermal_monitor/README, tools/thermal_monitor/mainwindow.cpp
=> Thermald 2 5 merge

tools/thermal_monitor/mainwindow.cpp
In some cases a trip element was not added for every zone, causing an
out-of-bound access to the trips vector (which is indexed by zone number).
In this change we ensure that a (possinly empty) trips element is added for
each zone.
=> Ensure there is one trips element per zone

man/thermal-conf.xml.5
The debian packaging lintian checker is complaining that some of the
lines in the manual are very long. Break these up to sub-80 char wide
lines to clean these warnings up.  Also, fix up the .IP formatting as
the intentation is a bit broken. Add bullet points in .IP formatting
for some style too.
Signed-off-by: Colin Ian King <colin.i.king@gmail.com>
=> Manual: thermal-conf.xml - clean up lintian warnings and .IP formatting

configure.ac, data/Makefile.am, data/org.freedesktop.thermald.conf.in, tools/thermal_monitor/README, tools/thermal_monitor/main.cpp
This means that distros can choose their pre-existing power management group
or just choose a less generic group than 'power' such as '_thermald-managers'.
Closes: https://github.com/intel/thermal_daemon/issues/162
See-also: https://bugs.debian.org/864502
=> Make the dbus power group configurable

README.txt, data/thermal-conf.xml, distribution_integration/chromeos_gentoo_ebuild_spec, distribution_integration/make_rpm.sh, distribution_integration/thermal-daemon.spec, docs/thermal_daemon-docs.xml, man/thermal-conf.xml.5, man/thermald.8, src/main.cpp, src/thd_cdev_intel_pstate_driver.cpp, src/thd_engine.cpp, src/thd_gddv.cpp, src/thd_trt_art_reader.cpp, src/thd_zone_cpu.cpp, src/thd_zone_cpu.h, test/cpufreq.sh, test/intel_pstate.sh, test/thermald_optimization_with_dptfxtract, tools/thermal_monitor/README, tools/thermal_monitor/thermaldinterface.cpp
- Fix typos and grammar
- Fix shell script header shebangs
- Fix regex for finding the current branch
- Switch from apt-get to apt for installing Ubuntu dependencies
- Drop mention of where qmake is installed
- Update links for https, redirects, moved repos and archived pages
- Fix dates in manual pages
- Drop empty/skipped .TP and .PP in manual pages
=> Clean up typos, grammar, shebangs, regex, commands, links, paths, manual pages

tools/thermal_monitor/ThermalMonitor.pro
The library name was changed to title case in QCustomPlot 2.1.0.
=> Update the QCustomPlot library name

src/acpi_thermal_rel_ioct.h
The current thermald source code uses ioctl numbers that are inconsistent with those used by the acpi_thermal_rel driver in the linux source tree. The effect of this mismatch is to cause a stack smash when running thermald against linux 6.5.3.
=> Fix incorrect ioctl numbers used for reading PSVT

src/thd_dbus_interface.cpp
Hi,
This patch includes
1. Set the default value of GError to NULL.
2. Remove unused codes.
https://github.com/intel/thermal_daemon/pull/429 already fixed the default value issue so the merge sequence could be https://github.com/intel/thermal_daemon/pull/429 and https://github.com/intel/thermal_daemon/pull/430
=> Fix GError Null pointer issue and remove unused codes.

src/thd_dbus_interface.cpp
This patch includes two fixes.
1. Unable to terminate through Dbus API.
2. Skip dbus-glib API when GDbus is used.
=> Fix unable to terminate through Dbus API

src/thd_gddv.cpp
The "Unsupported condition" are quite common on modern Intel CPUs. It's also expected as thermald doesn't have proper support for those conditions (and probably never will).
So lower the log level to make it less scary.
=> Downgrade log level on "Unsupported condition"

src/thd_cdev_rapl.cpp, src/thd_engine_default.cpp, src/thd_gddv.cpp
There are a handful of incorrect %d or %u format specifiers being used for integer values. Fix this.
Detected using cppcheck static code analysis.
=> Fix incorrect integer format specifiers

tools/thermal_monitor/ThermalMonitor.pro, tools/thermal_monitor/mainwindow.cpp, tools/thermal_monitor/tripsdialog.cpp
Remove deprecated qt interface. With this it can also build with QT6. But since the library name for libcustomplot is distro dependent, ThermalMonitor.pro, must be updated. Keep one of the line from the following:
LIBS += -lQCustomPlot
LIBS += -lqcustomplot
LIBS += -lqcustomplot-qt6
=> Thermal Monitor: Remove deprecated calls

tools/thermal_monitor/tripsdialog.cpp
When user clicks on trip temperature in the configure trip dialog, It used to display, Zone and trip type. With the commit to remove deprecated warning for QModelIndex::child(int row, int column), the "type" display was removed.
Add back "type" with suggested alternative QAbstractItemModel::index() and display.
=> Thermal Monitor: Add trip type back

src/thd_dbus_interface.cpp
gcc static analyzer warns that introspection_data is not being null checked which could lead to a potential null pointer dereference. Even though error is being checked, it seems prudent to add a null check on introspection_data to make the code more resiliant and also to silence static analysis warnings.
=> src: thd_dbus_interface: add extra sanity check on introspection_data

src/thd_gddv.cpp
There are a couple of file descriptor leaks on error handling returns paths. Fix these by fclosing the files before returning.
Detected using static analysis with cppcheck.
=> Fix file descriptor leaks on error return paths

src/thd_engine_adaptive.cpp
The opened dir descriptor is not being closed and is causing a resource leak. Close it.
Fixes: 3ea73d5fc460 ("Auto detect int3400 base path")
=> Fix resource leak on opened dir descriptor

src/thd_engine_default.cpp
Since Linux RAPL driver doesn't have separate enable/disable for clamping RAPL, don't reset RAPL enabled bit. With current enable/disable powercap interface, clamp bit is also reset. This allows power to stay above set power limit in some cases.
=> Don't reset clamp bit for MSR RAPL

src/thd_gddv.cpp
use %jd instead of %ld to print variable of time_t type otherwise on 32 bit system:
src/thd_gddv.cpp:457:41: error: format '%ld' expects argument of type 'long int', but argument 11 has type 'time_t' {aka 'long long int'} [-Werror=format=]
src/thd_gddv.cpp:457:41: error: format '%ld' expects argument of type 'long int', but argument 13 has type 'time_t' {aka 'long long int'} [-Werror=format=]
=> Use correct format specifier for time_t
