intel/thermal_daemon

src/thd_cdev_msr_rapl.cpp
src/thd_cdev_rapl.cpp
src/thd_engine_default.cpp

Just two minor changes found using:  scan-build -o /tmp/scanbuild make

Two minor changes found by clang static analysis

---

distribution_integration/thermal-daemon.spec

Updated spec to 1.5.3

---

src/thd_cdev_modem.cpp
tools/thermal_monitor/mainwindow.cpp
tools/thermal_monitor/qcustomplot/qcustomplot.cpp
tools/thermal_monitor/tripsdialog.cpp

Hi - just a few minor fixes found using some static analysis tools. Nothing too major here.

misc fixes, trying to get thermal_monitor in a state ready for packaging

---

README.txt
configure.ac
man/thermal-conf.xml.5
man/thermald.8
src/thd_cdev_backlight.cpp
src/thd_cdev_backlight.h
src/thd_engine.cpp
src/thd_engine_default.cpp
src/thd_engine_default.h
src/thd_sys_fs.cpp
src/thd_trt_art_reader.cpp
tools/thermal_monitor/thermaldinterface.cpp

Development 1 5

---

tools/thermal_monitor/ThermalMonitor.pro
tools/thermal_monitor/mainwindow.cpp
tools/thermal_monitor/qcustomplot/changelog.txt
tools/thermal_monitor/qcustomplot/qcustomplot.cpp
tools/thermal_monitor/qcustomplot/qcustomplot.h

Works with HiDPI and solves some other minor issues as well (see changelog.txt).
Builds and works fine on openSUSE Tumbleweed with Qt 5.7.1, I did not test other versions.

Update to QCustomPlot 2.0.0-beta

---

src/thd_parse.cpp
src/thd_parse.h
src/thd_zone_cpu.cpp

Just a couple of minor fixes to plug some holes found by static analysis.

Fix a couple of minor issues found using PVS-studio static analysis

---

distribution_integration/thermal-daemon.spec

distribution_integration: update RPM .spec for 1.6

---

src/thd_engine_default.cpp

There are some new fanless platforms use DPTF's virtual sensor instead
of INT340X devices.
Because of that, the _PSV is no longer in use, at least not directly,
hence its value may set higher then _CRT. To a fanless system that means
no cooling device gets activated before _CRT, so the system will be
considered overheated by Linux kernel, and gets shutdown by the kernel.
To avoid that, we use 85% of _CRT value as our new _PSV value.
A 15% margin below _CRT should be enough for passive cooling devices to
clamp the temperature down.
This is a compromise, but we need this until we have full DPTF support.

Honor ACPI _CRT for processor thermal zone

---

README.txt
man/thermal-conf.xml.5
src/thd_zone_cpu.h
test/test6.xml

Fix a handful of minor spelling mistakes.

Trivial spelling mistake/typos fixes

---

src/acpi_thermal_rel_ioct.h

Signed-off-by: Zhen Han <zhen.han@intel.com>

Add the license header of acpi_thermal_rel_ioct.h

---

src/thd_engine_default.h

Tracked-On: OAM-84253
Signed-off-by: ashish18590 <ashish18590@gmail.com>

[Fix][Thermal Daemon]: Fixing tcc_offset variable

---

src/main.cpp

Make timestamp logging more portable

---

autogen.sh
configure.ac
data/Makefile.am
data/org.freedesktop.thermald.conf

A few build fixes to make it easier to build thermald using jhbuild and other modern autoconf-aware tools.

Build fixes

---

data/thermald.service.in
src/main.cpp
src/thd_engine.cpp
src/thd_parse.cpp
src/thd_sensor.cpp
src/thd_sys_fs.cpp
src/thermald.h

See #237 
Note:
* This introduces `thd_log_msg` helper, which uses `g_message`
* Log `MESSAGE` severity by default
* Add some systemd integration to log using syslog then

Improve logging

---

tools/thermal_monitor/logdialog.ui
tools/thermal_monitor/pollingdialog.ui
tools/thermal_monitor/tripsdialog.ui

Refer to https://bugzilla.altlinux.org/41065
Reported-by: Vera Blagoveschenskaya <vercha@altlinux.org>
Signed-off-by: Nikolai Kostrigin <nickel@altlinux.org>

ui: cosmetic fixes to avoid label cut in dialogs

---

src/thd_engine_adaptive.cpp
src/thd_engine_default.cpp

Just a few more trivial fixes for warnings.

Some more coverity fixes

---

README.txt
configure.ac
src/thd_cdev.cpp
src/thd_engine_adaptive.cpp
src/thd_engine_adaptive.h
src/thd_gddv.cpp
src/thd_gddv.h
src/thd_trip_point.cpp
src/thd_trip_point.h

Development 2.5.1

---

src/thd_engine_adaptive.cpp
src/thd_gddv.cpp

Minor comment cleanup, no functional changes.
Signed-off-by: Colin Ian King <colin.i.king@gmail.com>

Fix a couple of spelling mistakes in comments.

---

src/thd_parse.cpp

Outputs were missing with --loglevel=info

Added ReadBack and DebouncePeriod to dump

---

src/thd_cdev_rapl.cpp
src/thd_engine_default.cpp
src/thd_gddv.cpp
src/thd_sensor_rapl_power.cpp

I ran cppcheck on the source, found some minor issues that can be cleaned-up.

Minor code clean-up janitorial fixes, address issues found with static analysis tool

---

Makefile.am
configure.ac
src/main.cpp
src/thd_dbus_interface.cpp
thermald-resource.gresource.xml
tools/thermald_set_pref.sh

Merge changes from
https://github.com/intel/thermal_daemon/pull/426
Separate pull request as the original pull couldn't be built.

V2.5.5 merge branch

---

Makefile.am
README.txt
configure.ac
src/7zTypes.h
src/LzmaDec.c
src/LzmaDec.h
src/thd_engine.cpp
src/thd_engine_adaptive.cpp
src/thd_gddv.cpp
src/thd_gddv.h
src/thd_int3400.cpp
src/thd_lzma_dec.cpp

V2.5.8 pre rel

---

src/thd_gddv.cpp
tools/thermal_monitor/README

Two minor spelling mistake fixings

---

test/thermald_debug_output_graph.py

There is a spelling mistake in a print statement, fix it.

test: Fix spelling mistake "Ploting" -> "Plotting"
